version: '3.9'

services:
  aggregator:
    build: .
    container_name: aggregator_service
    ports:
      - "8000:8000"
    networks:
      - internal_net

  publisher:
    image: python:3.11-slim
    container_name: publisher_service
    working_dir: /app
    volumes:
      - ./publisher:/app
    command: /bin/bash -c "pip install requests && python publisher.py"
    depends_on:
      - aggregator
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge
